Add ES384 support
firebase/php-jwt pull request #324
Opened 2021-03-29 13:57 UTC by sdrsdr

Taste case plus I've verified to be correctly working against ES384 token from NodeJS system

2021-03-29 14:00 UTC, sdrsdr commented
@googlebot I signed it!

2021-03-30 08:41 UTC, sdrsdr commented
@googlebot I signed it!

2021-05-16 09:47 UTC, BramRoets commented
@googlebot Is this blocked by anyhing? What can we do to get this merged? Thanks!

2021-05-16 17:21 UTC, sdrsdr commented
I guess we need a review but this repo is quite dead IMHO

2021-05-17 05:55 UTC, BramRoets commented
That's too bad .. I think it's the most used PHP JWT library at the moment...

2021-05-17 22:23 UTC, bshaffer commented
@sdrsdr it's not dead yet!!

Sorry for the late reply, I missed this PR. This is a fantastic addition, I'll review / merge today!

2021-05-17 22:27 UTC, bshaffer approved these changes

2021-05-17 22:35 UTC, bshaffer requested changes

2021-05-17 22:35 UTC, bshaffer commented on tests/JWTTest.php
> +        $decoded = JWT::decode($encoded, $publicKey, array('ES384'));
When I switch both occurences of `ES384` above to `ES256`, and likewise if I switch `ES256` to `ES384` in the test function `testEncodeAndDecodeEcdsaToken`, the tests still pass.  Can we use test-cases which are not interchangeable?

Also, since these two tests are so similar, it would be better to use a data provider:

```php
    /**
     * @runInSeparateProcess
     * @dataProvider provideEncodeAndDecodeToken
     */
    public function testEncodeAndDecodeToken($privateKeyFile, $publicKeyFile, $alg)
    {
        $privateKey = file_get_contents($privateKey);
        $payload = array('foo' => 'bar');
        $encoded = JWT::encode($payload, $privateKeyFile, $alg);

        // Verify decoding succeeds
        $publicKey = file_get_contents($publicKeyFile);
        $decoded = JWT::decode($encoded, $publicKey, array($alg));

        $this->assertEquals('bar', $decoded->foo);
    }

    public function provideEncodeAndDecodeToken()
    {
        return [
            [__DIR__ . '/ecdsa-private.pem', __DIR__ . '/ecdsa-public.pem', 'ES256'],
            [__DIR__ . '/ecdsa384-private.pem', __DIR__ . '/ecdsa384-public.pem', 'ES384'],
        ];
    }
```

2021-05-18 10:53 UTC, sdrsdr commented on tests/JWTTest.php
> +        $decoded = JWT::decode($encoded, $publicKey, array('ES384'));
ES384 and ES256 are meant to be interchangeable the test should and will fail  if you try to have only one place changed. I'm not really familiar with PHP code testing. PHP is not in my daily workset, I've long ago removed the setup on my pc needed for testing php code. Can you please merge it as is and then fix it to you liking?

2021-05-19 18:18 UTC, bshaffer approved these changes
will submit test refactor in another test

2021-05-19 18:19 UTC, merged

2021-05-31 17:19 UTC, BramRoets commented
@bshaffer Could you make a release including these changes? is there anything we can do to help this process?

Many thanks!

2021-05-31 17:21 UTC, bshaffer commented
@BramRoets tagged in [v5.3.0](https://github.com/firebase/php-jwt/releases/tag/v5.3.0)

2021-05-31 17:22 UTC, BramRoets commented
Wow that was quick! Thanks for the help.