Gracefully Prevent Keys from Ever Being Used for the Wrong Header-Specified Algorithm
firebase/php-jwt pull request #352
Opened 2021-08-04 09:43 UTC by paragonie-security

Proposed Fix for #321

This aims to provide backwards compatibility by guessing the algorithm for a key based on the key's contents, but it will likely fail in corner cases.

If this is merged, users **SHOULD** be explicit about the algorithms they're using.

i.e. Instead of $keyAsString, pass in (new JWTKey($keyAsString, 'ES384'))

2021-08-16 14:40 UTC, pwolanin requested changes

2021-08-16 14:40 UTC, pwolanin commented on src/JWT.php
> +        if ($key instanceof Keyring) {
Why hard-code this class?  It means I can't implement my own key database or just use an array of key objects.  There is verification below that the key type is as expected.

2021-08-16 14:40 UTC, pwolanin commented on src/JWT.php
> +        if (!static::verify("$headb64.$bodyb64", $sig, $key->getKeyMaterial(), $header->alg)) {
For better BC, just cast the key to string?

2021-08-16 14:40 UTC, pwolanin commented on src/JWT.php
> +        if (!($key instanceof JWTKey)) {
For BC, why not construct the object here if the key is a string and guess the alg?

2021-08-16 14:40 UTC, pwolanin commented on src/Keys/JWTKey.php
> +        return JWT::constantTimeEquals($this->alg, $headerAlg);
Why do you need const time comparison here?  The alg is generally known or picked from a short list.

2021-08-16 14:40 UTC, pwolanin commented on src/Keys/JWTKey.php
> +    public function getKeyMaterial()
Also implement __toSting() to return the key material?

2021-08-16 14:40 UTC, pwolanin commented on src/JWT.php
> +        if (!$key->isValidForAlg($header->alg)) {
It seems like the alg guessing code should allow multiple? e.g. if it's an RSA key type all the signature lengths should pass here.  The way it looks now, if RS512 and RS256 are supported by the endpoint, and a bare string key is passed in, a request with a header alg RS256 fails?

2021-09-08 13:10 UTC, paragonie-security commented on src/JWT.php
> +        if (!$key->isValidForAlg($header->alg)) {
We don't feel particularly strongly about the safety and correctness of this guessing code. We'd feel much safer if a major version bump with a small risk of BC breaks was elected instead.

2021-09-08 13:11 UTC, paragonie-security commented on src/JWT.php
> +        if ($key instanceof Keyring) {
Feel free to swap it out for an interface in your own implementation. This is just a proof-of-concept fix.

2021-11-02 23:43 UTC, bshaffer commented on src/Keys/JWTKey.php
> +    public function getKeyMaterial()
I'd rather be explicit with this

2021-11-03 17:37 UTC, bshaffer reviewed
The changes here causes our tests to fail in 6 different places. I think this is a significant enough number to indicate to me at least that these changes represent too large of a BC break for the current version.

I am in support of creating a major version release with these changes, and requiring the keys to represent a `Key` or `KeyRing` object instead of allowing a key without an algorithm. I think this is the better approach, rather than break a significant number of users with this change.

Thanks so much for your work on this!

2021-11-03 17:37 UTC, bshaffer commented on src/Keys/JWTKey.php
> +        } elseif ($length >= 220) {
Same issue here - the EC key generates with length `215`, and so the tests for EC keys fail.

2021-11-03 17:37 UTC, bshaffer commented on tests/Keys/JWTKeyTest.php
> +        );
This test also fails, I'm not sure why

2021-11-03 17:49 UTC, paragonie-security commented on src/Keys/JWTKey.php
> +        if ($length >= 720) {
This was a canned guess at key size. 1024-bit RSA is a bit dodgy; 3072-bit and higher is recommended.

2021-11-03 17:49 UTC, paragonie-security commented on src/Keys/JWTKey.php
> +        } elseif ($length >= 220) {
What curve are you using?

2021-11-03 17:50 UTC, paragonie-security commented on tests/Keys/JWTKeyTest.php
> +        );
This looks like a pasto. Line 48 should be `HS512` when compared with the lines below.

2021-11-03 17:54 UTC, paragonie-security commented on src/Keys/JWTKey.php
> +        if ($length >= 720) {
The other thing we could do is parse the base64-encoded string and inspect the ASN.1 header. That's probably a bit more reliable. I'll send a superseding pull request that does that instead.

2021-11-03 21:17 UTC, bshaffer commented on src/Keys/JWTKey.php
> +        } elseif ($length >= 220) {
The test you provided!

2021-11-03 21:21 UTC, bshaffer commented
@paragonie-security I've decided to avoid trying to guess the algorithm, and instead make providing an algorithm supported in `v5` and required in `v6`. Please see my PRs #365 (`v5`) and #364 (`v6`). 

I think providing a quick and easy way for users to upgrade is preferable to the almost certain breakage of existing implementations if we try detecting the algorithm. Please let me know what you think, and I would love a review of the above PRs as well, if it isn't too much trouble!!

2021-11-03 21:58 UTC, paragonie-security commented
Yes. We agree that algorithm guessing is dangerous. That's why we eschewed it in [the wrapper library](https://github.com/paragonie/php-jwt-guard) that addresses the issue.

This PR was always intended as a proof of concept for a fix, in case you were at a loss for how to tackle the changes. We're happy to review your PRs in favor of this one.

2021-11-03 21:58 UTC, closed without merging

2021-11-03 22:17 UTC, bshaffer commented
@paragonie-security Thank you so much for all of your help with this! I will await your review of my other PRs before merging.