feat: add cached keyset
firebase/php-jwt pull request #397
Opened 2022-02-08 15:59 UTC by bshaffer

see #384

2022-02-17 13:12 UTC, bshaffer commented
From @swiffer in another issue:

> Hi @bshaffer[](https://teams.googleplex.com/betterbrent@google.com) - first sorry for late response and thanks a lot for initial implementation.
> Coming from CakePHP and trying to use the new functionality there isn't that easy.
> There are to PSR for Caching (6 + 16). CakePHP only bundles a SimpleCache (PSR 16) compatible cache.
> Any reason why you've choosen one over the other?
> Symfony provides a class of converting caches back and forth via Cache adapter classes so this could be a viable solution: https://symfony.com/doc/current/components/cache/psr6_psr16_adapters.html

I'm replying here to keep it in this thread for review.

I do not have a reason for choosing PSR-6 over PSR-16. If there's a strong argument to supporting one over the other (or both) I'm all ears.

Why is it difficult to implement in CakePHP? Does the minimum requirement of PHP 8.0 have something to do with it, or is it because you're using PSR-16 instead?

2022-02-19 11:36 UTC, swiffer commented
cakephp/authentication 2.9.0 currently targets CakePHP 4.0 which requires >= PHP 7.2. this will be raised to PHP 7.4 in the next minor of CakePHP and PHP 8.0 in CakePHP 5.0. Therefore maybe it'll take some time until it can actually be used in the cakephp/authentication plugin but should work out. It's more that CakePHP only has a PSR 16 compatible cache implementation and introducing additional dependencies is increasing complexity.

2022-02-19 11:39 UTC, swiffer commented on src/CachedKeySet.php
> +        if (!isset($this->keySet[$keyId])) {
this code is currently not proof against ddos attacks via key spamming, or is it?

this scenario was described here: https://github.com/auth0/node-jwks-rsa#rate-limiting

2022-02-23 15:03 UTC, bshaffer commented on src/CachedKeySet.php
> +        if (!isset($this->keySet[$keyId])) {
No, it does not. We can add this to the cache without too much issue, however. I'll take a look. Thanks for pointing this out.

2022-02-23 15:05 UTC, bshaffer commented
> cakephp/authentication 2.9.0 currently targets CakePHP 4.0 which requires >= PHP 7.2.

I can cut a release with the minimum version at PHP 7.x (probably 7.1). 

> It's more that CakePHP only has a PSR 16 compatible cache implementation

This is a design decision by CakePHP, and doesn't really indicate so much what would be better for this repo. So unless it's possible to support both (which would require PHP 8.0 union types), I'd prefer to stick with PSR-6 unless there's a better argument to switch.

2022-04-13 06:13 UTC, mortenhauberg commented
Hi @bshaffer,

Is there anything I can do to move this forward?

2022-04-13 15:12 UTC, bshaffer commented
@mortenhauberg thanks for the ping! And yes, if you'd like to give it a review, that'd be very helpful.

2022-04-13 19:06 UTC, mortenhauberg approved these changes
I've made a few minor suggestions.
Some might call them nitpicks - feel free to ignore them 😃

I would like to bump `phpspec/prophecy-phpunit` to v2, though, but that would break support for PHP 7.1 and 7.2.
Maybe you want to consider dropping support for those versions by now anyway since they've [been unsupported for a while](https://www.php.net/supported-versions.php).

<img width="600" alt="oiAN8kiFgGN9mrIoOh0QxkSP3Nddqqy8@2x" src="https://user-images.githubusercontent.com/3660049/163251917-50d6ec11-6e84-43b6-9e9f-42cb03c78be2.png">


That would remove the deprecation warnings from PHPUnit and would be as simple as bumping the version and adding a trait in `tests/CachedKeySetTest.php`.

I can do that if you'd like.

Btw, I can see a bunch of old issues still being open.
Let me know if you like some help with those 🙂

2022-04-13 22:02 UTC, bshaffer commented
@mortenhauberg Thanks for your review! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA). For more information, open the [CLA check for this pull request](https://github.com/firebase/php-jwt/pull/397/checks?check_run_id=6015300221).

As for dropping support for PHP 7.1 and 7.2, I cringe at the idea of leaving some developers in the lurch because of testing libraries. If I'm going to drop PHP support, I want a better reason than that. And truthfully, the very end of 2020 (When 7.2 dropped support) was less than a year and a half ago, which is not very long in the relatively slow moving world of PHP.

2022-04-14 09:35 UTC, mortenhauberg commented
@bshaffer CLA signed 👍🏻

I didn't necessarily mean for you to bump the supported versions _now_, and I do agree that doing it for the sake of a few tests is a bad reason. 

I can also see that you still have users stuck on older versions. https://github.com/firebase/php-jwt/pull/399#issuecomment-1098782870

So I totally see your point 😊 
But 7.1/7.2/7.3 is EOL, and at some point, you should probably drop support. 
Anyway, it's not my call, and I'm happy if I could help move this forward. 

Please let me know if there's anything else I can do

2022-04-14 10:12 UTC, glen-84 commented
Despite the fact that we're on PHP 7.0, I actually agree with dropping support for EOL versions of PHP.

We shouldn't be using this version for many reasons, and if libraries don't drop support, then they're essentially enabling the use of potentially insecure software. This is even more relevant for a library dealing with aspects of security.

Yes, backporting one or two features to 6.0.x would be useful to us, but that's ultimately "our problem" – in the case of the linked issue, we can either stick with RSA, or consider backporting it ourselves (with or without an official 6.0.x release, though that would be nice).

2022-04-23 05:51 UTC, dwsupplee requested changes
Just a few minor notes so far, still working through the core of the logic in the CacheKeySet and the tests.

2022-04-23 05:51 UTC, dwsupplee commented on src/CachedKeySet.php
> + * @template-implements ArrayAccess<string, Key>
Is this supported by phpstan? I've only noticed `@implements` as its own annotation [here](https://phpstan.org/writing-php-code/phpdocs-basics#generics).

2022-04-23 05:51 UTC, dwsupplee commented on src/CachedKeySet.php
> +     * @var int
```suggestion
     * @var ?int
```

2022-04-25 14:12 UTC, bshaffer commented on README.md
> +    $cacheItemPool
Good catch!!

2022-04-25 14:30 UTC, bshaffer commented on README.md
> +$decoded = JWT::decode($payload, $keySet);
You're right! `$payload` is actually the wrong variable name based on the rest of these samples. It should be `$jwt`. I've renamed it.

I could define `$jwt`, but it would be hard to illustrate (since in the case of a public JWKS URI, the private key would be not available to whoever is decoding the JWT). I think since it's defined earlier in the README, it would be sufficient to define it in a way that makes this clear?

```php
$jwt = 'eyJhbGci...`; // Some JWT signed by a key from the public JWKS
```

2022-04-25 14:45 UTC, bshaffer commented on src/CachedKeySet.php
> + * @template-implements ArrayAccess<string, Key>
You're right that `@template-implements` doesn't seem to exist... I am not sure how that got in there :P

But also, I don't think `@template` serves a purpose here either. The template annotation is [for generics](https://phpstan.org/blog/generics-in-php-using-phpdocs#type-variables), and we aren't implementing generics here. So I believe the return typing of the methods is sufficient. I think it's better to just remove this. What do you think?

2022-04-25 14:47 UTC, bshaffer commented on src/CachedKeySet.php
> + * @template-implements ArrayAccess<string, Key>
Okay, [@template-implements does exist](https://coder-question.com/cq-blog/570077), but it doesn't really fit here either.

2022-04-25 21:11 UTC, bshaffer commented on src/CachedKeySet.php
> + * @template-implements ArrayAccess<string, Key>
Well, I removed it and it broke, so it _was_ doing something. I added `@implements` instead of `@template-implements`, and that also works. So I'm kinda confused as to how this all just went down, but the important thing is it works now, so I'm satisfied. Also, `@implements` makes more sense in this case anyway. So thanks! Good catch.

2022-04-25 21:13 UTC, bshaffer commented on README.md
> +$decoded = JWT::decode($payload, $keySet);
added!

2022-04-27 22:26 UTC, merged